name: Monitor de Sessões Databricks

on:
  schedule:
    - cron: '0 * * * *'  # Corre de hora em hora (minuto 0)
  workflow_dispatch:      # Permite que você clique num botão para testar agora

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Instalar bibliotecas
        run: |
          pip install requests beautifulsoup4

      - name: Executar Script de Monitorização
        env:
          # Estas variáveis ficam escondidas no GitHub (passo 3 abaixo)
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python selenium2.py

      - name: Salvar progresso (Commit and Push)
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add last_count.txt
          # O '|| exit 0' serve para não dar erro se não houver mudança no arquivo
          git commit -m "chore: update session count [skip ci]" || exit 0
          git push